# Generated by Django 4.2.4 on 2023-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
